In [2]:
import numpy as np
import cv2

In [3]:
img = cv2.imread('../data/friends.jpg')

cv2.imshow("Friends Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
# Load the Cascade Classifier
haar = cv2.CascadeClassifier('../algorithm/haarcascade_frontalface_default.xml')

In [5]:
# Image copy
image = img.copy()

# Convert the image to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Apply gray scale image to Cascade Classifier
face_rect_box = haar.detectMultiScale(gray, 1.3, 3)

# Draw bounding box
for x, y, w, h in face_rect_box:
    cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)

cv2.imshow('Face Detection', image)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
print(face_rect_box) ## First - x, second - y, third -  width, fourth - height

[[256  88  98  98]
 [127 107  97  97]
 [405  90  99  99]]


## Real Time Face Recognition in OpenCv (Video)

In [12]:
cap = cv2.VideoCapture('../data/video.mp4')

while cap.isOpened():

    ret, frame = cap.read()

    if not ret:
        break

    image = frame.copy()

    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    face_rect_box = haar.detectMultiScale(gray, 1.3, 5)

    for x, y, w, h in face_rect_box:
        cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)

    cv2.imshow('Frame Face Detection', image)

    key = cv2.waitKey(10) & 0xFF

    # Press ESC or q to quit
    if key == 27 or key == ord('q'):
        break

    # Detect if window was manually closed
    if cv2.getWindowProperty('Frame Face Detection', cv2.WND_PROP_VISIBLE) < 1:
        break

cap.release()
cv2.destroyAllWindows()

    
 